### ISSUE TITLE
Larger fonts on larger devices

### ISSUE THREAD

**Issue by made4this** [le-cds/connectiq-faceymcwatchface#22]
First of all: this is great work! Got garmin on your wrist? Then try this out!
Second of all: I'd appreciate to have a little larger icons and/or letters on vívoactive 4 as it seems that there is some more space to be filled :)

Thank you so much!

**Comment by le-cds** [comment]
I've carefully adjusted font and icon sizes, with the following result:

![watchface-font](https://user-images.githubusercontent.com/7465584/100481581-c7f7ee80-30f4-11eb-8432-e2fa210540fb.png)

I was careful not to overcrowd the interface, so the changes are subtle. To really see the difference, compare the width of the time line.
